ALTER TABLE events ADD COLUMN image_focal_x REAL NOT NULL DEFAULT 50;
ALTER TABLE events ADD COLUMN image_focal_y REAL NOT NULL DEFAULT 50;
ALTER TABLE events ADD COLUMN image_fit TEXT NOT NULL DEFAULT 'contain';
